import assert from 'node:assert/strict';
import { cp, mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chromium } from 'playwright-core';

const root = await mkdtemp(path.join(tmpdir(), 'page-builder-refresh-'));
const source = path.join(root, 'source'); await cp('dist/ui/vendor/b2b', source, { recursive: true });
const built = await readFile('dist/server.js');
await mkdir(path.join(root, 'libraries'));
await writeFile(path.join(root, 'libraries/settings.json'), JSON.stringify({ currentSnapshotId: 'b2b-0000000000000000', autoRefreshPageIds: ['legacy-page'] }));
const child = spawn(process.execPath, ['dist/standalone.js'], { env: { ...process.env, PAGE_BUILDER_DATA_DIR: path.join(root, 'pages'), PAGE_BUILDER_LIBRARY_DIR: path.join(root, 'libraries'), PAGE_BUILDER_EXPORT_DIR: path.join(root, 'exports') }, stdio: ['ignore', 'pipe', 'inherit'] });
const url = await new Promise((resolve, reject) => {
  const timer = setTimeout(() => reject(Error('server timeout')), 15000); let text = '';
  child.stdout.on('data', data => { text += data; const match = text.match(/http:\/\/127\.0\.0\.1:\d+/); if (match) { clearTimeout(timer); resolve(match[0]); } });
  child.once('exit', code => { clearTimeout(timer); reject(Error(`server exit ${code}`)); });
});
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = []; page.on('pageerror', error => errors.push(error.message));
let libraryRequests = 0; page.on('request', request => { if (/\/api\/libraries\/(refresh|check)$/.test(request.url())) libraryRequests++; });
const api = async (route, data) => { const result = await fetch(url + route, data ? { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) } : {}); return { status: result.status, ...await result.json() }; };
try {
  await page.goto(url);
  assert.equal((JSON.parse(await readFile(path.join(root, 'libraries/settings.json'), 'utf8'))).autoRefreshPageIds, undefined);
  assert.equal(await page.getByText('自动刷新当前页面', { exact: true }).count(), 0);
  await page.getByLabel('添加卡片').click(); await page.getByText('卡片已添加').waitFor();
  const pageId = (await api('/api/pages')).pages[0].pageId;
  const original = (await api('/api/pages/' + pageId)).page;
  await page.locator('.component-shell').first().click();
  const appearance = () => page.getByRole('group', { name: '外观', exact: true });
  await appearance().locator('[data-select-trigger]').getByText('有边框', { exact: true }).waitFor();
  await appearance().locator('[data-select-trigger]').click();
  assert.equal(await appearance().getByRole('option').count(), 2);
  assert.equal(await appearance().getByRole('option', { name: '有边框', exact: true }).count(), 1);
  assert.equal(await appearance().getByRole('option', { name: '无边框', exact: true }).count(), 1);
  await appearance().getByRole('option', { name: '无边框', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#canvas .source-design-card')?.classList.contains('is-borderless'));
  assert.equal((await api('/api/pages/' + pageId)).page.root.children[0].props.appearance, 'borderless');
  await appearance().locator('[data-select-trigger]').click();
  await appearance().getByRole('option', { name: '有边框', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('#canvas .source-design-card')?.classList.contains('is-borderless'));
  const border = () => page.locator('#canvas .source-design-card').evaluate(el => getComputedStyle(el).borderTopColor);
  const before = await border();
  const loader = path.join(source, 'components/runtime/loader.js');
  await writeFile(loader, (await readFile(loader, 'utf8')).replace('function loadScript(url) {', 'function loadScript (url) {'));
  const style = path.join(source, 'components/C-34-card/styles.css');
  await writeFile(style, '@import "./source-update.css";\n' + (await readFile(style, 'utf8')).replace('var(--b2b-color-border-surface)', 'var(--integration-border)'));
  const extra = path.join(source, 'components/C-34-card/source-update.css'); await writeFile(extra, ':root{--integration-border:rgb(123,45,67)}');
  // Public protocol metadata is read from this independently changed source, not a plugin copy.
  const schema = path.join(source, 'components/runtime/api-schema.js');
  await writeFile(schema, (await readFile(schema, 'utf8')) + '\nwindow.B2B.components.apiSchemas["C-02"].props.label.description = "独立更新的公开说明";\nwindow.B2B.components.apiSchemas["C-34"].props.appearance.values = ["bordered"];\nwindow.B2B.components.apiSchemas["C-34"].props.reviewNote = {type:"string",default:"新属性默认值"};\n');
  await page.getByText('组件库来源与更新', { exact: true }).click();
  await page.locator('#library-source input').fill(source);
  await page.waitForTimeout(6500); // Cross the retired 5-second timer interval.
  assert.equal(libraryRequests, 0, 'opening the editor must not check or update the component source');
  assert.equal(await border(), before);
  await page.getByRole('button', { name: '刷新并重载组件', exact: true }).click();
  await page.waitForFunction(() => { const el = document.querySelector('#canvas .source-design-card'); return el && getComputedStyle(el).borderTopColor === 'rgb(123, 45, 67)'; }, null, { timeout: 30000 });
  const first = await api('/api/pages/' + pageId);
  assert.notEqual(first.page.componentLibrary.snapshotId, original.componentLibrary.snapshotId);
  assert.deepEqual(first.page.root, original.root);
  assert.equal(first.components.find(item => item.id === 'C-02').props.label.description, '独立更新的公开说明');
  assert.ok(first.library.files.includes('components/C-34-card/source-update.css'));
  const exported = await api(`/api/pages/${pageId}/export`, {}); assert.equal(exported.export.revision, first.page.revision);
  await page.getByText('组件库来源与更新', { exact: true }).click();
  await page.locator('.component-shell').first().click();
  await appearance().locator('[data-select-trigger]').click();
  assert.equal(await appearance().getByRole('option').count(), 1, 'enum choices must follow the refreshed source schema');
  assert.equal(await appearance().getByRole('option', { name: '有边框', exact: true }).count(), 1);
  await appearance().getByRole('option', { name: '有边框', exact: true }).click();
  await page.getByText('其他设置', { exact: true }).click();
  assert.equal(await page.locator('#inspector details').getByRole('group', { name: 'reviewNote', exact: true }).locator('input').inputValue(), '新属性默认值', 'new schema properties must appear without rebuilding the plugin');
  await page.locator('#inspector details').getByRole('group', { name: 'reviewNote', exact: true }).locator('input').fill('未提交的备注');
  await page.locator('#library-source input').focus();
  await writeFile(extra, ':root{--integration-border:rgb(23,145,67)}');
  const requestsBeforeDraft = libraryRequests;
  await page.getByRole('button', { name: '刷新并重载组件', exact: true }).click();
  await page.locator('#library-update-status').filter({ hasText: '请先应用其他设置' }).waitFor();
  assert.equal(libraryRequests, requestsBeforeDraft, 'refresh must not discard unapplied properties');
  assert.equal(await border(), 'rgb(123, 45, 67)');
  await page.locator('#inspector details').getByRole('button', { name: '应用其他设置', exact: true }).click();
  await page.locator('#save-state').getByText('已保存', { exact: true }).waitFor();
  assert.equal((await api('/api/pages/' + pageId)).page.root.children[0].props.reviewNote, '未提交的备注');
  original.root.children[0].props.reviewNote = '未提交的备注';
  await page.getByRole('button', { name: '刷新并重载组件', exact: true }).click();
  await page.waitForFunction(() => { const el = document.querySelector('#canvas .source-design-card'); return el && getComputedStyle(el).borderTopColor === 'rgb(23, 145, 67)'; }, null, { timeout: 30000 });
  const second = await api('/api/pages/' + pageId); assert.deepEqual(second.page.root, original.root);
  // A later source change still requires an explicit refresh.
  await writeFile(extra, ':root{--integration-border:rgb(33,65,167)}');
  await page.getByText('组件库来源与更新', { exact: true }).click();
  await page.getByRole('button', { name: '刷新并重载组件', exact: true }).click();
  await page.waitForFunction(() => { const el = document.querySelector('#canvas .source-design-card'); return el && getComputedStyle(el).borderTopColor === 'rgb(33, 65, 167)'; }, null, { timeout: 30000 });
  const third = await api('/api/pages/' + pageId);
  // Reload also works without a source change, without adding a page revision.
  await page.getByText('组件库来源与更新', { exact: true }).click();
  await Promise.all([page.waitForEvent('load'), page.getByRole('button', { name: '刷新并重载组件', exact: true }).click()]);
  await page.locator('#canvas .source-design-card').waitFor();
  assert.deepEqual((await api('/api/pages/' + pageId)).page, third.page);
  // Failed source updates leave both the current page and default library intact.
  await writeFile(schema, (await readFile(schema, 'utf8')).replace('"C-02": {', '"C-02X": {'));
  await page.getByText('组件库来源与更新', { exact: true }).click();
  await page.getByRole('button', { name: '刷新并重载组件', exact: true }).click();
  await page.locator('#library-update-status').filter({ hasText: '组件库资源或公开协议无效' }).waitFor({ timeout: 20000 });
  const failed = await api('/api/pages/' + pageId); assert.deepEqual(failed.page, third.page);
  assert.equal((await api('/api/libraries')).currentSnapshotId, third.page.componentLibrary.snapshotId);
  assert.equal(await border(), 'rgb(33, 65, 167)');
  assert.deepEqual(await readFile('dist/server.js'), built);
  assert.deepEqual(errors, []);
  await page.screenshot({ path: '/tmp/page-builder-independent-refresh.png' });
  console.log(JSON.stringify({ manualRefresh: true, unappliedPropertiesPreserved: true, noAutomaticLibraryRequests: true, legacyAutoSettingRemoved: true, repeatedManualRefresh: true, contentPreserved: true, noPluginRebuild: true, loaderWhitespaceAccepted: true, additionalCssDependencyLoaded: true, sourceMetadataRefreshed: true, failedUpdatePreservedPage: true, before, after: await border(), buildSha256: createHash('sha256').update(built).digest('hex') }));
} finally { await browser.close(); child.kill('SIGTERM'); }
